### ISSUE TITLE
Error in React-Talk

### ISSUE THREAD

**Issue by AndrewMerke** [lahsivjar/react-talk#25]
I am getting error:
`Uncaught (in promise) TypeError: this.props.messages.map is not a function`

In React-talk index.js

I am doing everything exact like in your demo example:
```
<TalkBox topic="Chat" currentUserId={ this.randomUserId }
          currentUser={ this.randomUserName } messages={ this.state.messages }
          onSendMessage={ this.sendMessage } connected={ this.state.clientConnected }/>
```

**Comment by lahsivjar** [comment]
Please post the full stacktrace along with your file where you declare TalkBox

**Comment by AndrewMerke** [comment]
You can delete this post, that was my own problem :)
